name: remote ssh command
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH command using password
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |

            docker stop edward
            docker rm edward
            doker build -t edward. 
            docker run -d -p 9000:9000 --name edward 
